name: Update versions.json

on:
  release:
    types: [published]

# CẤP QUYỀN GHI CHO GITHUB_TOKEN
permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # persist credentials để có thể push bằng GITHUB_TOKEN
          persist-credentials: true
          fetch-depth: 0

      - name: Update versions.json
        run: |
          TAG=${GITHUB_REF##*/}
          URL=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$TAG \
            | jq -r '.assets[0].browser_download_url')
          FILE=versions.json
          [ ! -f "$FILE" ] && echo "{}" > $FILE
          jq --arg v "$TAG" --arg url "$URL" \
            '. + {($v): {version:$v, url:$url}}' \
            $FILE > tmp.json && mv tmp.json $FILE
          echo "Updated versions.json:" && cat $FILE

      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add versions.json
          git diff --staged --quiet || git commit -m "Update versions.json for $TAG"
          git push origin HEAD:main
